apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-mvn-push
spec:
  params:
  - default: ssh://git@bitbucket.arbetsformedlingen.se:7999/team-cicd/jboss-eap-helloworld-rs.git
    description: git url
    name: url
    type: string
  - default: master
    name: revision
    type: string
  - default: nexus.arbetsformedlingen.se/app-af-nexus-example/jboss-eap-helloworld-rs-joske
    description: image to build
    name: IMAGE
    type: string
  - default: "true"
    name: useProxy
    type: string
  - default: "false"
    description: Execute sonarscan
    name: runSonarScan
    type: string
  - default: none
    description: set when running sonar scan
    name: SONAR_PROJECT_KEY
    type: string
  - default: gcr.io/cloud-builders/mvn:3.5.0-jdk-8
    name: MAVEN_IMAGE
    type: string
  - default: image-registry.openshift-image-registry.svc:5000/team-cicd-images/eap73-af:latest
    description: baseimage
    name: BASEIMAGE
    type: string
  - default: target
    description: Path to build artifacts
    name: TARGET
    type: string
  - default: ear,war,jar
    description: Valid artifacts extensions to deploy
    name: EXTENSIONS
    type: string
  tasks:
  - name: git-clone
    params:
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "true"
    - name: deleteExisting
      value: "true"
    - name: verbose
      value: "true"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:af7dd5b3b1598a980f17d5f5d3d8a4b11ab4f5184677f7f17ad302baa36bd3c1
    - name: userHome
      value: /tekton/home
    - name: url
      value: $(params.url)
    - name: revision
      value: $(params.revision)
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: source
  - name: maven-af
    params:
    - name: GOALS
      value: clean package
    - name: CONTEXT_DIR
      value: .
    - name: MAVEN_IMAGE
      value: $(params.MAVEN_IMAGE)
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: maven-af
    workspaces:
    - name: maven-repo
      workspace: maven-repo
    - name: maven-settings
      workspace: maven-settings
    - name: source
      workspace: source
  - name: buildah-eap73-af
    params:
    - name: BASEIMAGE
      value: $(params.BASEIMAGE)
    - name: TLSVERIFY
      value: "true"
    - name: IMAGE
      value: $(params.IMAGE)
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:e19cf23d5f1e0608f5a897f0a50448beb9f8387031cca49c7487ec71bd91c4d3
    - name: TARGET
      value: $(params.TARGET)
    - name: EXTENSIONS
      value: $(params.EXTENSIONS)
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:af7dd5b3b1598a980f17d5f5d3d8a4b11ab4f5184677f7f17ad302baa36bd3c1
    runAfter:
    - maven-af
    taskRef:
      kind: Task
      name: buildah-eap73-af
    workspaces:
    - name: source
      workspace: source
    - name: image-storage
      workspace: image-storage
  - name: sonarqube-scanner-eap73-af
    params:
    - name: SONAR_HOST_URL
      value: http://sonarqube.arbetsformedlingen.se
    - name: SONAR_MAVEN_IMAGE
      value: gcr.io/cloud-builders/mvn:3.5.0-jdk-8
    - name: SONAR_PROJECT_KEY
      value: org.jboss.eap.quickstarts:helloworld-rs
    - name: useProxy
      value: "true"
    - name: proxyHost
      value: testproxy.admz.ams.se
    - name: proxyPort
      value: "8080"
    - name: nonProxyHosts
      value: .ams.se|.arbetsformedlingen.se|.cluster.local|.svc|10.0.0.0/8|10.132.120.0/24|10.144.0.0/14|127.0.0.1|164.135.0.0/16|172.30.0.0/16|172.30.0.0/25|ams.se|api-int.tocp4.arbetsformedlingen.se|arbetsformedlingen.se|cluster.local|localhost|svc
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: sonarqube-scanner-eap73-af
    when:
    - input: $(params.runSonarScan)
      operator: in
      values:
      - "true"
    workspaces:
    - name: source
      workspace: source
    - name: sonar-settings
      workspace: sonar-settings
  workspaces:
  - name: source
  - name: maven-repo
  - name: maven-settings
  - name: sonar-settings
    optional: true
  - name: image-storage
