apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-maven-build
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
