apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-image-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ocs-storagecluster-ceph-rbd
