apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  labels:
    app.kubernetes.io/version: "0.2"
  name: maven-af-large
spec:
  description: This Task can be used to run a Maven build.
  params:
  - default: gcr.io/cloud-builders/mvn:3.5.0-jdk-8
    description: Maven base image
    name: MAVEN_IMAGE
    type: string
  - default: clean package
    description: maven goals to run
    name: GOALS
    type: string
  - default: .
    description: The context directory within the repository for sources on which
      we want to execute maven goals.
    name: CONTEXT_DIR
    type: string
  steps:
  - env:
    - name: TMPDIR
      value: /tmp
    - name: MAVEN_OPTS
      value: -Xms128m -Xmx512m -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
        -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=256m
        -XX:ParallelGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1
        -XX:CICompilerCount=2 -XX:+ExitOnOutOfMemoryError
    image: $(params.MAVEN_IMAGE)
    name: mvn-goals
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "2"
        memory: 2Gi
    script: |
      #!/usr/bin/env sh

      export MAVEN_OPTS="-Xms512m -Xmx1024m -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=512m -XX:ParallelGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -XX:CICompilerCount=2 -XX:+ExitOnOutOfMemoryError"
      echo $MAVEN_OPTS

      USE_MAVEN_CACHE=""
      if [ "$(workspaces.maven-repo.bound)" = "true" ]; then
        USE_MAVEN_CACHE="-Dmaven.repo.local=$(workspaces.maven-repo.path)/m2/repository"
        PATH=$(workspaces.maven-repo.path)/maven/bin:$PATH
      fi

      USE_MAVEN_SETTINGS=""
      if [ "$(workspaces.maven-settings.bound)" = "true" ]; then
        USE_MAVEN_SETTINGS="-s $(workspaces.maven-settings.path)/settings.xml"
      fi

      echo "mvn $USE_MAVEN_SETTINGS $USE_MAVEN_CACHE $(params.GOALS)"
      mvn $USE_MAVEN_SETTINGS $USE_MAVEN_CACHE $(params.GOALS)
    workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
  workspaces:
  - description: The workspace consisting of maven project.
    name: source
  - description: The workspace consisting of maven repo cache.
    name: maven-repo
    optional: true
  - description: The workspace consisting of the custom maven settings provided by
      the configmap maven-settings
    name: maven-settings
