apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/instance: nodejs-tekton
    app.kubernetes.io/name: nodejs-tekton
    pipeline.openshift.io/runtime: nodejs
    pipeline.openshift.io/runtime-version: 14-ubi8
    pipeline.openshift.io/type: kubernetes
  name: nodejs-build-tekton
spec:
  params:
  - default: nodejs-tekton-app
    name: APP_NAME
    type: string
  - default: https://github.com/ych0537/nodejs-tekton-guide.git
    name: GIT_REPO
    type: string
  - default: master
    name: GIT_REVISION
    type: string
  - default: image-registry.openshift-image-registry.svc:5000/user-joske/nodejs-tekton-app:latest
    name: IMAGE_NAME
    type: string
  - default: nodejs
    name: PATH_CONTEXT
    type: string
  - default: registry.access.redhat.com/ubi8/nodejs-14@sha256:b241d5bdc8015baaeed0bbf66d2f934e72fa0b52263d62ce6b259ef343a0e6a7
    name: NODEJS_IMAGE
    type: string
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace-guide
  - name: build
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME)
    - name: TLSVERIFY
      value: "true"
    - name: PATH_CONTEXT
      value: $(params.PATH_CONTEXT)
    - name: NODEJS_IMAGE
      value: $(params.NODEJS_IMAGE)
    runAfter:
    - fetch-repository
    taskRef:
      kind: Task
      name: s2i-nodejs-af
    workspaces:
    - name: source
      workspace: workspace-guide
  workspaces:
  - name: workspace-guide
