apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nodejs-tekton-deploy
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ocs-storagecluster-ceph-rbd
