apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-nodejs-tekton-guide
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: bitbucket-push
    template:
      ref: trigger-template-nodejs-tekton-guide
